# Generated by Django 4.1.5 on 2023-01-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_studentmodel_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='roll',
        ),
    ]
